### ISSUE TITLE
_get_buffer_name throws uncaught Exception

### ISSUE THREAD

**Issue by ambasta** [kiddos/deoplete-cpp#1]
```
    def _get_buffer_name(self, context):
        if context['bufname'].endswith('.ino'):
            buffer_name = context['bufname'].replace('.ino', '.cpp')
        if context['bufname'].endswith('.cu'):
            buffer_name = context['bufname'].replace('.cu', '.cpp')
        return os.path.join(context['cwd'], buffer_name)
```

First of all, if context['bufname'] matches neither, the return will still try to join cwd with the buffer_name. This would be an exception since buffer_name is unassigned.

Secondly, on my local system, context['bufname'] is the same as the filename. Which means it would never end with .cu/.ino What gives?

**Comment by kiddos** [comment]
Thanks for noticing this
try [this](https://github.com/kiddos/deoplete-cpp/commit/3e0c892dadd0ec17810db80110326ab281c3bdab)
I kinda forgot to push the latest code. :P

**Comment by kiddos** [comment]
cuda completion is kinda funky right now
kernel function like `some_kernel<<<datasize/blocksize, blocksize>>>()` will not be complete
I can only do so much with libclang
I am thinking to pull online document to parse it and display completion result
